### ISSUE TITLE
The image has been removed?

### ISSUE THREAD

**Issue by duwei54** [wekan/wekan-gogs#7]
>docker-compose up -d
Pulling wekan-gogs (toroid/wekan-gogs:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

I try search from https://hub.docker.com,but find nothing

**Comment by andresmanelli** [comment]
I'll try to look at this today, but this project in a little bit outdated as the swimlanes ar not taken into account.

I haven't used this project for a while. Let us know if you can use it.

Did you try building the image?

**Comment by duwei54** [comment]
I just want to use it to build a bridge between wekan and gogs.  but I only find this project.

**Comment by andresmanelli** [comment]
Hey, I just pushed https://hub.docker.com/r/toroid/wekan-gogs

As I said, swimlanes are not taken into account, so I don't know if this project works know out of the box.

It should not take much effort to add swimlanes, but for the moment I don't have much time, sorry.

**Comment by duwei54** [comment]
@andresmanelli thank u  very very  much! ヾ(@^▽^@)ノ

**Comment by andresmanelli** [comment]
Hello, I pushed toroid/wekan-gogs:0.1.1 to docker hub a moment ago.

Note that the image will work fine once https://github.com/wekan/wekan/pull/1876 gets merged

**Comment by duwei54** [comment]
very excellent
